# Simple GitLab CI/CD configuration for Python projects
# For more detailed configuration options and expansion ideas, see the CI/CD Guide: [CI/CD Guide](CI_CD_Guide.md)


variables:
  CODE_PATH: "path/to/your/code"  # Base path to code for linting and testing

stages:
  - install
  - lint
  - test

# Install Dependencies
install_dependencies:
  stage: install
  image: python:3.12
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  cache:
    paths:
      - .cache/pip
  artifacts:
    paths:
      - venv

# Linting
lint:
  stage: lint
  image: python:3.12
  script:
    - source venv/bin/activate
    - flake8 $CODE_PATH
    - black --check $CODE_PATH

# Testing with Multiple Python Versions
test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11", "3.12"]
  image: python:$PYTHON_VERSION
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest $CODE_PATH/tests/ --junitxml=junit/test-report.xml --cov=$CODE_PATH
  artifacts:
    reports:
      junit: junit/test-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
