"""Preprocessing configuration.

This module centralizes the location of the raw simulation outputs that are
converted into ML-ready datasets by `0.extract_ML_data.ipynb`.

The preprocessing notebook expects `Config.input_dir` to be a directory
containing *multiple* HDF5 files (one per grid / scenario) generated by the
upstream GridExpand pipeline (powerflow + urbs outputs).
"""


class Config:
    """Configuration container for the preprocessing notebook.

    Attributes:
        input_dir: Absolute path to a folder containing PostPowerflow HDF5 files.
    """

    input_dir = "/dss/dssfs04/lwp-dss-0002/pn98cu/pn98cu-dss-0000/EliasH/PostPowerflow"
    # input_dir = "/dss/dssfs05/lwp-dss-0003/pn98cu/pn98cu-dss-0001/EliasH/PostPowerflow"

config = Config()