-- Transformer expansion rows of one synthetic analysis (one per selected power-flow run with a rating):
-- the peaks of transformer_peak.sql joined with the decisions of the rules (temp table
-- expansion_station_selection, written by synthetic_materialization). estimated_cost_eur carries every
-- station-level cost (exchange, load transfer, new substations, voltage measures).
INSERT INTO surrogrid.expansion_transformer_result (
    expansion_analysis_run_id,
    powerflow_run_id,
    grid_case_id,
    scenario_id,
    ags,
    plz,
    kcid,
    bcid,
    pylovo_grid_result_id,
    pylovo_version_id,
    transformer_rated_power_kva,
    transformer_equipment_name,
    max_s_mva,
    max_p_mw,
    max_q_mvar,
    loading_percent,
    required_transformer_kva,
    additional_transformer_kva,
    requires_expansion,
    overloaded_at_100_percent,
    estimated_cost_eur,
    transformer_cost_basis,
    critical_t_index,
    critical_ts,
    station_measure,
    station_limit_kva,
    excess_kva,
    transformer_exchange_cost_eur,
    load_transfer_cost_eur,
    new_station_cost_eur,
    voltage_measure,
    voltage_cost_eur
)
SELECT
    :expansion_analysis_run_id,
    tp.powerflow_run_id,
    tp.grid_case_id,
    tp.scenario_id,
    tp.ags,
    tp.plz,
    tp.kcid,
    tp.bcid,
    tp.pylovo_grid_result_id,
    tp.pylovo_version_id,
    tp.rated_kva,
    tp.transformer_equipment_name,
    tp.s_mva,
    tp.p_mw,
    tp.q_mvar,
    tp.loading_percent,
    GREATEST(sel.required_kva, tp.rated_kva),
    GREATEST(sel.required_kva - tp.rated_kva, 0.0),
    sel.requires_expansion,
    tp.loading_percent > 100.0,
    sel.estimated_cost_eur,
    sel.transformer_cost_basis,
    tp.critical_t_index,
    tp.critical_ts,
    sel.station_measure,
    sel.station_limit_kva,
    sel.excess_kva,
    sel.transformer_exchange_cost_eur,
    sel.load_transfer_cost_eur,
    sel.new_station_cost_eur,
    sel.voltage_measure,
    sel.voltage_cost_eur
FROM expansion_transformer_peak tp
JOIN expansion_station_selection sel USING (powerflow_run_id)
