"""Source-preserving physical-building and demand-component helpers.

The PyLoVo mixed-use contract keeps topology physical-building scoped while
representing electricity demand as at most one residential and one
non-residential component.  This module is deliberately independent of the
database and HDF5 layers so both handoff paths apply exactly the same rules.
"""

from __future__ import annotations

from collections.abc import Iterable

import numpy as np
import pandas as pd


RESIDENTIAL = "Residential"
NONRESIDENTIAL_CATEGORIES = frozenset({"Commercial", "Public"})
AREA_RTOL = 1e-6
AREA_ATOL_M2 = 1e-5

PHYSICAL_SOURCE_COLUMNS = (
    "objectid",
    "floor_area",
    "floor_number",
    "residential_floor_area",
    "nonresidential_floor_area",
    "nonresidential_use",
    "households",
    "occupants",
    "building_use",
    "building_use_id",
    "building_type",
    "mix_score",
    "mix_rule",
    "mix_confidence",
    "residential_peak_load_in_kw",
    "nonresidential_peak_load_in_kw",
    "nonresidential_mv_direct",
    "peak_load_in_kw",
    "bus",
)

COMPONENT_COLUMNS = (
    "component_id",
    "grid_case_id",
    "objectid",
    "pylovo_grid_result_id",
    "pylovo_version_id",
    "component_category",
    "effective_floor_area_m2",
    "gross_floor_area_m2",
    "households",
    "occupants",
    "installed_peak_kw",
    "load_units",
    "consumer_vertex",
    "bus",
    "included_in_lv",
    "mv_direct",
    "mix_score",
    "mix_rule",
    "mix_confidence",
    "source_building_use",
    "source_building_use_id",
    "source_building_type",
)


def _missing_columns(frame: pd.DataFrame, columns: Iterable[str]) -> list[str]:
    return sorted(set(columns).difference(frame.columns))


def _numeric(frame: pd.DataFrame, column: str) -> pd.Series:
    return pd.to_numeric(frame[column], errors="coerce")


def validate_physical_buildings(
    buildings: pd.DataFrame,
    *,
    require_grid_identity: bool = False,
) -> pd.DataFrame:
    """Validate and return one source row per physical building.

    No source classification is derived or rewritten here.  Missing columns
    indicate an input generated by an unsupported pre-mixed contract and are a
    hard error.
    """
    if not isinstance(buildings, pd.DataFrame):
        raise TypeError("Physical buildings must be provided as a pandas DataFrame.")
    missing = _missing_columns(buildings, PHYSICAL_SOURCE_COLUMNS)
    if require_grid_identity:
        missing.extend(_missing_columns(buildings, ("pylovo_grid_result_id", "pylovo_version_id")))
    if missing:
        raise ValueError(
            "Mixed-capable physical-building input is missing required columns: "
            f"{sorted(set(missing))}"
        )

    result = buildings.copy()
    object_ids = result["objectid"].astype("string").str.strip()
    if object_ids.isna().any() or object_ids.eq("").any():
        raise ValueError("Every physical building must have a non-empty objectid.")
    if object_ids.duplicated().any():
        duplicates = sorted(object_ids[object_ids.duplicated(keep=False)].unique().tolist())
        raise ValueError(f"Physical building objectid values must be unique: {duplicates[:5]}")
    result["objectid"] = object_ids.astype(str)

    numeric_columns = (
        "floor_area",
        "floor_number",
        "residential_floor_area",
        "nonresidential_floor_area",
        "households",
        "occupants",
        "residential_peak_load_in_kw",
        "nonresidential_peak_load_in_kw",
        "peak_load_in_kw",
    )
    numeric = {column: _numeric(result, column) for column in numeric_columns}
    finite = {
        column: numeric[column].notna()
        & np.isfinite(numeric[column].to_numpy(dtype=float, na_value=np.nan))
        for column in numeric_columns
    }
    for column in (
        "floor_area",
        "floor_number",
        "residential_floor_area",
        "nonresidential_floor_area",
    ):
        if (~finite[column]).any() or numeric[column].lt(0).any():
            raise ValueError(f"Physical-building {column} must be finite and non-negative.")
    if numeric["floor_number"].eq(0).any() and (
        numeric["residential_floor_area"].gt(0)
        | numeric["nonresidential_floor_area"].gt(0)
    ).any():
        raise ValueError("A building with positive component area must have a positive floor_number.")

    gross_area = numeric["floor_area"] * numeric["floor_number"]
    component_area = numeric["residential_floor_area"] + numeric["nonresidential_floor_area"]
    if not np.allclose(component_area, gross_area, rtol=AREA_RTOL, atol=AREA_ATOL_M2):
        bad = (~np.isclose(component_area, gross_area, rtol=AREA_RTOL, atol=AREA_ATOL_M2))
        examples = result.loc[bad, "objectid"].tolist()[:5]
        raise ValueError(
            "Residential and non-residential effective areas must sum to gross "
            f"floor area within tolerance; examples={examples}"
        )

    nonres_use = result["nonresidential_use"].astype("string").str.strip()
    nonres_area = numeric["nonresidential_floor_area"]
    invalid_nonres_use = nonres_area.gt(0) & ~nonres_use.isin(NONRESIDENTIAL_CATEGORIES)
    if invalid_nonres_use.any():
        examples = result.loc[invalid_nonres_use, ["objectid", "nonresidential_use"]].to_dict("records")[:5]
        raise ValueError(
            "Positive non-residential area requires nonresidential_use Commercial "
            f"or Public; examples={examples}"
        )

    residential_area = numeric["residential_floor_area"]
    residential_mask = residential_area.gt(0)
    households = numeric["households"]
    occupants = numeric["occupants"]
    residential_peak = numeric["residential_peak_load_in_kw"]
    invalid_residential = residential_mask & (
        households.isna()
        | households.le(0)
        | occupants.isna()
        | occupants.lt(0)
        | residential_peak.isna()
        | residential_peak.le(0)
    )
    if invalid_residential.any():
        examples = result.loc[
            invalid_residential,
            ["objectid", "households", "occupants", "residential_peak_load_in_kw"],
        ].to_dict("records")[:5]
        raise ValueError(
            "Positive residential area requires positive households, non-negative "
            f"occupants, and a positive residential peak; examples={examples}"
        )

    nonres_peak = numeric["nonresidential_peak_load_in_kw"]
    invalid_nonres_peak = nonres_area.gt(0) & (nonres_peak.isna() | nonres_peak.le(0))
    if invalid_nonres_peak.any():
        examples = result.loc[
            invalid_nonres_peak,
            ["objectid", "nonresidential_peak_load_in_kw"],
        ].to_dict("records")[:5]
        raise ValueError(
            "Positive non-residential area requires a positive non-residential "
            f"peak; examples={examples}"
        )

    direct_source = result["nonresidential_mv_direct"]
    invalid_direct = direct_source.map(
        lambda value: not pd.isna(value)
        and not isinstance(value, (bool, np.bool_))
    )
    if invalid_direct.any():
        raise ValueError("nonresidential_mv_direct must contain boolean values.")
    direct = direct_source.fillna(False).astype(bool)
    if (direct & nonres_area.eq(0)).any():
        raise ValueError("nonresidential_mv_direct can only be true for a positive non-residential component.")

    if result["bus"].isna().any():
        examples = result.loc[result["bus"].isna(), "objectid"].tolist()[:5]
        raise ValueError(f"Every physical building must map to one consumer bus: {examples}")
    return result


def build_building_components(
    buildings: pd.DataFrame,
    *,
    grid_case_id: int | None = None,
) -> pd.DataFrame:
    """Build the deterministic long-form component manifest.

    The returned frame has one row for every positive source component.  An
    excluded MV-direct non-residential component remains visible in the frame.
    """
    physical = validate_physical_buildings(buildings)
    if grid_case_id is not None:
        physical["grid_case_id"] = int(grid_case_id)
    elif "grid_case_id" not in physical:
        physical["grid_case_id"] = pd.NA

    rows: list[dict[str, object]] = []
    for _, building in physical.sort_values("objectid", kind="stable").iterrows():
        object_id = str(building["objectid"])
        gross_area = float(building["floor_area"]) * float(building["floor_number"])
        common = {
            "grid_case_id": building.get("grid_case_id"),
            "objectid": object_id,
            "pylovo_grid_result_id": building.get("pylovo_grid_result_id"),
            "pylovo_version_id": building.get("pylovo_version_id"),
            "gross_floor_area_m2": gross_area,
            "consumer_vertex": building.get("consumer_vertex", building.get("vertice_id")),
            "bus": building["bus"],
            "mix_score": building["mix_score"],
            "mix_rule": building["mix_rule"],
            "mix_confidence": building["mix_confidence"],
            "source_building_use": building["building_use"],
            "source_building_use_id": building["building_use_id"],
            "source_building_type": building["building_type"],
        }
        residential_area = float(building["residential_floor_area"])
        if residential_area > 0:
            rows.append(
                {
                    **common,
                    "component_id": f"{object_id}::residential",
                    "component_category": RESIDENTIAL,
                    "effective_floor_area_m2": residential_area,
                    "households": building["households"],
                    "occupants": building["occupants"],
                    "installed_peak_kw": building["residential_peak_load_in_kw"],
                    "load_units": float(building["households"]),
                    "included_in_lv": True,
                    "mv_direct": False,
                }
            )
        nonresidential_area = float(building["nonresidential_floor_area"])
        if nonresidential_area > 0:
            category = str(building["nonresidential_use"]).strip()
            direct = bool(building["nonresidential_mv_direct"])
            rows.append(
                {
                    **common,
                    "component_id": f"{object_id}::{category.lower()}",
                    "component_category": category,
                    "effective_floor_area_m2": nonresidential_area,
                    "households": pd.NA,
                    "occupants": pd.NA,
                    "installed_peak_kw": building["nonresidential_peak_load_in_kw"],
                    "load_units": 1.0,
                    "included_in_lv": not direct,
                    "mv_direct": direct,
                }
            )

    components = pd.DataFrame(rows, columns=COMPONENT_COLUMNS)
    if components.empty:
        raise ValueError("The selected grid contains no positive demand components.")
    if components["component_id"].duplicated().any():
        raise ValueError("Component IDs must be unique within a grid case.")

    counts = components.groupby("objectid", sort=False)["component_category"].agg(list)
    invalid = counts.map(lambda values: len(values) > 2 or values.count(RESIDENTIAL) > 1 or len(set(values) - {RESIDENTIAL}) > 1)
    if invalid.any():
        raise ValueError(
            "Each physical building may have at most one Residential and one "
            f"non-residential component: {invalid[invalid].index.tolist()[:5]}"
        )
    return components.reset_index(drop=True)


def validate_component_bus_metadata(
    components: pd.DataFrame,
    load_metadata: pd.DataFrame,
) -> None:
    """Check included component categories against bus-level PyLoVo loads.

    This intentionally validates bus/category sets only; load rows do not carry
    a reliable building foreign key and are never joined one-to-one to objects.
    """
    required = {"bus", "category"}
    missing = required.difference(load_metadata.columns)
    if missing:
        raise ValueError(f"PyLoVo load metadata is missing columns: {sorted(missing)}")
    expected = set(
        zip(
            components.loc[components["included_in_lv"], "bus"].astype(int),
            components.loc[components["included_in_lv"], "component_category"].astype(str),
        )
    )
    actual = set(
        zip(
            pd.to_numeric(load_metadata["bus"], errors="coerce").dropna().astype(int),
            load_metadata.loc[load_metadata["category"].notna(), "category"].astype(str),
        )
    )
    missing_pairs = sorted(expected.difference(actual))
    if missing_pairs:
        raise ValueError(
            "Included component categories are absent from PyLoVo bus load "
            f"metadata: {missing_pairs[:5]}"
        )


def residential_component_mask(components: pd.DataFrame) -> pd.Series:
    """Return the residential components eligible for LV demand and heat."""
    return components["included_in_lv"].astype(bool) & components["component_category"].eq(RESIDENTIAL)

